In [2]:
import numpy as np
np_array = np.array([1,2,3,4])
np_array

array([1, 2, 3, 4])

In [7]:
a = np.array([1,2,3])
b = np.array([1.0, 2, 3])

print(f'a type: {a.dtype}, b type:{b.dtype}')

b = b.astype(np.int64)
print(f'New b type: {b.dtype}')

a type: int64, b type:float64
New b type: int64


In [ ]:
v = np.array([10, 20, 30, 40]) # 1D (en kolumn)
m = np.array([[1,2,3], 
              [4,5,6]]) # 2D (2 rader, 3 kolumner)

print(f'Shape: {v.shape}')
print(f'Shape: {m.shape}')


Shape: (4,)
Shape: (2, 3)


In [13]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
x = np.array([10, 20, 30, 40])
y = np.array([1,2,3,4])

print(x + y )
print(x * 2 )
print(y * 2 )
print(x ** 2 )
print(f'Mean: {x.mean()}')
print(f'Standard diviation: : {x.std()}')
print(f'Min: {x.min()}')
print(f'Max: {x.max()}')





[11 22 33 44]
[20 40 60 80]
[2 4 6 8]
[ 100  400  900 1600]
Mean: 25.0
Standard diviation: : 11.180339887498949
Min: 10
Max: 40


In [34]:
m = np.array([[1,2,3],
              [4,5,6]])
v = np.array([10, 20, 30])

m_plus_v = m + v
print(m_plus_v)


[[11 22 33]
 [14 25 36]]


In [44]:
col = np.array([[10], [100]]) # shape(2, 1)
new_col = m + col
new_col



array([[ 11,  12,  13],
       [104, 105, 106]])

In [53]:
try: 
    new_cl = np.array([1,2,3]).reshape(3, 1) + np.array([10, 20, 30])  # (3, 1) + (2,) -> mismatch
except ValueError as e:
    print(f'fel: {e}')
print(new_cl)


[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [56]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [57]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [58]:
# np.ones((3,2)) + np.ones((2,3))

In [86]:
z = np.arange(12).reshape(3, 4)  # (3 rows and 4 columns)
print(z,'\n')
print(z[0, 1])
print(z[1])
print(f'Ger ut första kolumnen: {z[:, 0]}\n') # ger ut första kolumnen
print(f'Kolumn 1 och kolumn 2:\n {z[:, 1:3]}')




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

1
[4 5 6 7]
Ger ut första kolumnen: [0 4 8]

Kolumn 1 och kolumn 2:
 [[ 1  2]
 [ 5  6]
 [ 9 10]]


In [93]:
mask = z % 2 == 0


mask, z[mask]

(array([[ True, False,  True, False],
        [ True, False,  True, False],
        [ True, False,  True, False]]),
 array([ 0,  2,  4,  6,  8, 10]))

In [94]:
scores = np.array([50, 60, 70, 80, 90], dtype=np.float64)

z = (scores - scores.mean()) / scores.std()
scores.mean(), scores.std(), z.round(2)

(np.float64(70.0),
 np.float64(14.142135623730951),
 array([-1.41, -0.71,  0.  ,  0.71,  1.41]))